name: ci-hypermode-functions

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ">=20"
      - name: Locate directory with hypermode.json
        id: set-dir
        run: |
          HYPERMODE_DIR=$(find $(pwd) -name 'hypermode.json' -print0 | xargs -0 -n1 dirname)
          echo "HYPERMODE_DIR=$HYPERMODE_DIR" >> $GITHUB_ENV
          cd $HYPERMODE_DIR/functions
      - name: Install dependencies
        run: npm install
      - name: Build the project
        run: npm run build release
      - name: Publish GitHub artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            ${{ env.HYPERMODE_DIR }}/hypermode.json
            ${{ env.HYPERMODE_DIR }}/functions/build/*
